### ISSUE TITLE
Constraints after bad conditions are still triggered 

### ISSUE THREAD

**Issue by jcelerier** [OSSIA/API#8] opened 2015-11-17 16:39 UTC
As can be seen in this picture.
First condition is 1 == 1, second condition is 1 == 2

![bad](https://cloud.githubusercontent.com/assets/2772730/11217712/077720b8-8d52-11e5-8029-a9ddf5761c98.png)

[bad_condition.scorejson.txt](https://github.com/OSSIA/API/files/36923/bad_condition.scorejson.txt)

**Comment by theod** [comment] 2015-11-18 14:43
I'm looking at this trouble.
for the record I can't build such kind of scenario myself. when I click on parentEvent and if I edit the condition it appears on the highest event only. but maybe this is not available on master ?

**Comment by theod** [comment] 2015-11-18 14:57
hum ... I can't reproduce this trouble on my side (I did a clean and fresh build after updating i-score and API on master)

**Comment by theod** [comment] 2015-11-18 15:00
ok I've managed to recreate the scenario myself too : I forgot about the split feature (which not user friendly but this is another topic)

**Comment by theod** [comment] 2015-11-19 22:52
this seems to be fixed.
actually I've never encountered such trouble during the whole dev I did recently on execution (testing trigger and condition) so I close the issue

**Closed by theod** 2015-11-19 22:52 UTC
